### ISSUE TITLE
Switch to pom-scijava parent

### ISSUE THREAD

**Issue by imagejan** [mpicbg-scicomp/Interactive-H-Watershed#2]
`pom-imagej` is now deprecated in favor of `pom-scijava`

Switching to `pom-scijava` 14.0.0 would require the following:

* Add required properties (e.g. license, scm, ...) to `pom.xml` (see [here](https://github.com/scijava/pom-scijava-base#enforcer-rules-declared-in-this-parent))
* The `SCF_ImgTools` dependency would have to be deployed (to Maven Central, or to `maven.imagej.net`) so others can build the code.

**Comment by benoitlo** [comment]
Hi @imagejan ,
Thanks for the comments. The pom-scijava update is on my todo list. Regarding the second point, I totally forgot about that :-/. That is definitely a problem. In the short term I might just make the tool stand alone as there are few dependency. I'll check the feasability and will do that shortly.

**Comment by benoitlo** [comment]
The parent pom was updated to pom-scijava 14.0.0
The dependency to SCF_imgTools making so anyone can be build the code from that repo

@imagejan, thanks for pointing that out! If you have a chance to give it a try and let me know how it went that would be great.

**Comment by imagejan** [comment]
To make `mvn` succeed, I had to add the `imglib2-ij` dependency. I opened https://github.com/mpicbg-scicomp/Interactive-H-Watershed/pull/3 for this.

👍

**Comment by benoitlo** [comment]
Hi @imagejan, 
Interesting, it compiles fine for me with 2 different machines. I compile the Maven project from Eclipse with the context menu Run as>Maven build is there any difference with the command you run to compile? Not that I mind adding the dependency (I will) but I try to understand the difference of behavior to avoid the issue next time.

**Comment by imagejan** [comment]
I usually run `mvn` from the command line to be absolutely sure. Building in eclipse depends on a bunch of configurations and your local classpath settings that might not have been carried on to the git repository.

**Comment by benoitlo** [comment]
Thanks for the feedback. I just merged the modification you proposed.
